name: Pages (staging + prod)

on:
  pull_request: { branches: [dev] }      # PR → ephemeral preview
  push:
    branches: [ dev ]                    # push to dev → staging
    tags: [ 'v*' ]                       # tag v1.2 → production

permissions: { contents: read, pages: write, id-token: write }
concurrency: { group: pages, cancel-in-progress: true }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v3
        with: { path: . }

  deploy-staging:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/dev'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - id: deploy
        uses: actions/deploy-pages@v4

  deploy-production:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - id: deploy
        uses: actions/deploy-pages@v4
